version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: game_db
    environment:
      POSTGRES_USER: game_user
      POSTGRES_PASSWORD: game_password
      POSTGRES_DB: game_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U game_user -d game_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: game_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/game_db
      SPRING_DATASOURCE_USERNAME: game_user
      SPRING_DATASOURCE_PASSWORD: game_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: